version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/site/hugo"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
